//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: protocol/snake.proto
namespace Snake3D
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _AccountId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AccountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AccountId
    {
      get { return _AccountId; }
      set { _AccountId = value; }
    }
    private int _ThemeType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ThemeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ThemeType
    {
      get { return _ThemeType; }
      set { _ThemeType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRes")]
  public partial class LoginRes : global::ProtoBuf.IExtensible
  {
    public LoginRes() {}
    
    private int _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private float _RoomW;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomW", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float RoomW
    {
      get { return _RoomW; }
      set { _RoomW = value; }
    }
    private float _RoomH;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RoomH", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float RoomH
    {
      get { return _RoomH; }
      set { _RoomH = value; }
    }
    private float _StartX;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"StartX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float StartX
    {
      get { return _StartX; }
      set { _StartX = value; }
    }
    private float _StartY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"StartY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float StartY
    {
      get { return _StartY; }
      set { _StartY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}