//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: protocol/test.proto
namespace Snake
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MyRequest")]
  public partial class MyRequest : global::ProtoBuf.IExtensible
  {
    public MyRequest() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _website;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"website", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string website
    {
      get { return _website?? @"http://www.paotiao.com/"; }
      set { _website = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool websiteSpecified
    {
      get { return this._website != null; }
      set { if (value == (this._website== null)) this._website = value ? this.website : (string)null; }
    }
    private bool ShouldSerializewebsite() { return websiteSpecified; }
    private void Resetwebsite() { websiteSpecified = false; }
    
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data?? null; }
      set { _data = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataSpecified
    {
      get { return this._data != null; }
      set { if (value == (this._data== null)) this._data = value ? this.data : (byte[])null; }
    }
    private bool ShouldSerializedata() { return dataSpecified; }
    private void Resetdata() { dataSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}