// Code generated by protoc-gen-go.
// source: snake.proto
// DO NOT EDIT!

/*
Package snake is a generated protocol buffer package.

It is generated from these files:
	snake.proto

It has these top-level messages:
	Login
	Move
*/
package snake

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Login struct {
	// 账号
	AccountId *string `protobuf:"bytes,1,opt,name=AccountId" json:"AccountId,omitempty"`
	// 皮肤
	ThemeType *int32 `protobuf:"varint,2,opt,name=ThemeType" json:"ThemeType,omitempty"`
	// 账号
	RoomId *int32 `protobuf:"varint,3,opt,name=RoomId" json:"RoomId,omitempty"`
	// 房间宽
	RoomW *float32 `protobuf:"fixed32,4,opt,name=RoomW" json:"RoomW,omitempty"`
	// 房间高
	RoomH *float32 `protobuf:"fixed32,5,opt,name=RoomH" json:"RoomH,omitempty"`
	// 玩家出生位置X
	StartX *float32 `protobuf:"fixed32,6,opt,name=StartX" json:"StartX,omitempty"`
	// 玩家出生位置Y
	StartY           *float32 `protobuf:"fixed32,7,opt,name=StartY" json:"StartY,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Login) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *Login) GetThemeType() int32 {
	if m != nil && m.ThemeType != nil {
		return *m.ThemeType
	}
	return 0
}

func (m *Login) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *Login) GetRoomW() float32 {
	if m != nil && m.RoomW != nil {
		return *m.RoomW
	}
	return 0
}

func (m *Login) GetRoomH() float32 {
	if m != nil && m.RoomH != nil {
		return *m.RoomH
	}
	return 0
}

func (m *Login) GetStartX() float32 {
	if m != nil && m.StartX != nil {
		return *m.StartX
	}
	return 0
}

func (m *Login) GetStartY() float32 {
	if m != nil && m.StartY != nil {
		return *m.StartY
	}
	return 0
}

type Move struct {
	// 账号
	AccountId *string `protobuf:"bytes,1,opt,name=AccountId" json:"AccountId,omitempty"`
	// 移动点x
	PosX *float32 `protobuf:"fixed32,2,opt,name=PosX" json:"PosX,omitempty"`
	// 移动点y
	PosY             *float32 `protobuf:"fixed32,3,opt,name=PosY" json:"PosY,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Move) Reset()                    { *m = Move{} }
func (m *Move) String() string            { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()               {}
func (*Move) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Move) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *Move) GetPosX() float32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *Move) GetPosY() float32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

func init() {
	proto.RegisterType((*Login)(nil), "Login")
	proto.RegisterType((*Move)(nil), "Move")
}

func init() { proto.RegisterFile("snake.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xce, 0x4b, 0xcc,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xaa, 0xe6, 0x62, 0xf5, 0xc9, 0x4f, 0xcf, 0xcc,
	0x13, 0x12, 0xe4, 0xe2, 0x74, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xf1, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x04, 0x09, 0x85, 0x64, 0xa4, 0xe6, 0xa6, 0x86, 0x54, 0x16, 0xa4, 0x4a, 0x30,
	0x29, 0x30, 0x6a, 0xb0, 0x0a, 0xf1, 0x71, 0xb1, 0x05, 0xe5, 0xe7, 0xe7, 0x7a, 0xa6, 0x48, 0x30,
	0x83, 0xf9, 0xbc, 0x5c, 0xac, 0x20, 0x7e, 0xb8, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0x13, 0x8c, 0xeb,
	0x21, 0xc1, 0x0a, 0xe6, 0xf2, 0x71, 0xb1, 0x05, 0x97, 0x24, 0x16, 0x95, 0x44, 0x48, 0xb0, 0xa1,
	0xf0, 0x23, 0x25, 0xd8, 0x41, 0x7c, 0x25, 0x53, 0x2e, 0x16, 0xdf, 0xfc, 0xb2, 0x54, 0x6c, 0x76,
	0xf3, 0x70, 0xb1, 0x04, 0xe4, 0x17, 0x47, 0x80, 0xad, 0x65, 0x82, 0xf2, 0x22, 0xc1, 0x96, 0x32,
	0x01, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xe2, 0xaf, 0xdd, 0xc1, 0x00, 0x00, 0x00,
}
