// Code generated by protoc-gen-go.
// source: snake.proto
// DO NOT EDIT!

/*
Package snake is a generated protocol buffer package.

It is generated from these files:
	snake.proto

It has these top-level messages:
	MsgMsgData
	MsgMsgInit
	MsgPosInfo
	MsgPlayerInfo
	MsgLogin
	MsgMove
	MsgPosStruct
	MsgAddTargetPos
	MsgFoodStruct
	MsgAddFood
	MsgDelFood
	MsgRoomData
	MsgRoomInfo
	MsgRoomEnter
	MsgExitRoom
	MsgError
	MsgHeartbeat
*/
package snake

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 错误提示码
type TErrorType int32

const (
	// 无效
	TErrorType_Invalid TErrorType = 0
	// 房间号为空
	TErrorType_RoomIdIsNull TErrorType = 1
	// 该玩家不在房间中
	TErrorType_PlayerNoInRoom TErrorType = 2
	// 该玩家已经在房间中
	TErrorType_PlayerInRoom TErrorType = 3
	// 该玩家不存在
	TErrorType_PlayerIsNo TErrorType = 4
	// 其他设备登录
	TErrorType_OtherLogin TErrorType = 5
)

var TErrorType_name = map[int32]string{
	0: "Invalid",
	1: "RoomIdIsNull",
	2: "PlayerNoInRoom",
	3: "PlayerInRoom",
	4: "PlayerIsNo",
	5: "OtherLogin",
}
var TErrorType_value = map[string]int32{
	"Invalid":        0,
	"RoomIdIsNull":   1,
	"PlayerNoInRoom": 2,
	"PlayerInRoom":   3,
	"PlayerIsNo":     4,
	"OtherLogin":     5,
}

func (x TErrorType) Enum() *TErrorType {
	p := new(TErrorType)
	*p = x
	return p
}
func (x TErrorType) String() string {
	return proto.EnumName(TErrorType_name, int32(x))
}
func (x *TErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TErrorType_value, data, "TErrorType")
	if err != nil {
		return err
	}
	*x = TErrorType(value)
	return nil
}
func (TErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TPosShapeType int32

const (
	// 方形
	TPosShapeType_Square TPosShapeType = 0
	// 圆形
	TPosShapeType_Round TPosShapeType = 1
)

var TPosShapeType_name = map[int32]string{
	0: "Square",
	1: "Round",
}
var TPosShapeType_value = map[string]int32{
	"Square": 0,
	"Round":  1,
}

func (x TPosShapeType) Enum() *TPosShapeType {
	p := new(TPosShapeType)
	*p = x
	return p
}
func (x TPosShapeType) String() string {
	return proto.EnumName(TPosShapeType_name, int32(x))
}
func (x *TPosShapeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TPosShapeType_value, data, "TPosShapeType")
	if err != nil {
		return err
	}
	*x = TPosShapeType(value)
	return nil
}
func (TPosShapeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MsgMsgData struct {
	// id
	MsgId *uint32 `protobuf:"varint,1,opt,name=MsgId" json:"MsgId,omitempty"`
	// 消息名字
	MsgName          *string `protobuf:"bytes,2,opt,name=MsgName" json:"MsgName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgMsgData) Reset()                    { *m = MsgMsgData{} }
func (m *MsgMsgData) String() string            { return proto.CompactTextString(m) }
func (*MsgMsgData) ProtoMessage()               {}
func (*MsgMsgData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgMsgData) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *MsgMsgData) GetMsgName() string {
	if m != nil && m.MsgName != nil {
		return *m.MsgName
	}
	return ""
}

// 初始化消息id,服务器注册列表0为该消息
type MsgMsgInit struct {
	MsgList          []*MsgMsgData `protobuf:"bytes,1,rep,name=MsgList" json:"MsgList,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MsgMsgInit) Reset()                    { *m = MsgMsgInit{} }
func (m *MsgMsgInit) String() string            { return proto.CompactTextString(m) }
func (*MsgMsgInit) ProtoMessage()               {}
func (*MsgMsgInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgMsgInit) GetMsgList() []*MsgMsgData {
	if m != nil {
		return m.MsgList
	}
	return nil
}

// 点信息
type MsgPosInfo struct {
	// x
	PosX *float32 `protobuf:"fixed32,1,opt,name=PosX" json:"PosX,omitempty"`
	// y
	PosY             *float32 `protobuf:"fixed32,2,opt,name=PosY" json:"PosY,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgPosInfo) Reset()                    { *m = MsgPosInfo{} }
func (m *MsgPosInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgPosInfo) ProtoMessage()               {}
func (*MsgPosInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MsgPosInfo) GetPosX() float32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *MsgPosInfo) GetPosY() float32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

// 玩家信息
type MsgPlayerInfo struct {
	// 账号
	AccountId *string `protobuf:"bytes,1,opt,name=AccountId" json:"AccountId,omitempty"`
	// 房间id
	RoomId *uint32 `protobuf:"varint,2,opt,name=RoomId" json:"RoomId,omitempty"`
	// 朝向x
	DirectionX *float32 `protobuf:"fixed32,3,opt,name=DirectionX" json:"DirectionX,omitempty"`
	// 朝向y
	DirectionY *float32 `protobuf:"fixed32,4,opt,name=DirectionY" json:"DirectionY,omitempty"`
	// 速度
	Speed *float32 `protobuf:"fixed32,5,opt,name=Speed" json:"Speed,omitempty"`
	// 长度
	SurplusLength *uint32 `protobuf:"varint,6,opt,name=SurplusLength" json:"SurplusLength,omitempty"`
	// 坐标列表(从头到尾)
	PosList          []*MsgPosInfo `protobuf:"bytes,7,rep,name=PosList" json:"PosList,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MsgPlayerInfo) Reset()                    { *m = MsgPlayerInfo{} }
func (m *MsgPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgPlayerInfo) ProtoMessage()               {}
func (*MsgPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MsgPlayerInfo) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *MsgPlayerInfo) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MsgPlayerInfo) GetDirectionX() float32 {
	if m != nil && m.DirectionX != nil {
		return *m.DirectionX
	}
	return 0
}

func (m *MsgPlayerInfo) GetDirectionY() float32 {
	if m != nil && m.DirectionY != nil {
		return *m.DirectionY
	}
	return 0
}

func (m *MsgPlayerInfo) GetSpeed() float32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *MsgPlayerInfo) GetSurplusLength() uint32 {
	if m != nil && m.SurplusLength != nil {
		return *m.SurplusLength
	}
	return 0
}

func (m *MsgPlayerInfo) GetPosList() []*MsgPosInfo {
	if m != nil {
		return m.PosList
	}
	return nil
}

// 登录,C发送账号到S,S回复不带参数
type MsgLogin struct {
	AccountId        *string `protobuf:"bytes,1,opt,name=AccountId" json:"AccountId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgLogin) Reset()                    { *m = MsgLogin{} }
func (m *MsgLogin) String() string            { return proto.CompactTextString(m) }
func (*MsgLogin) ProtoMessage()               {}
func (*MsgLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MsgLogin) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

// 移动,C发摇杆的值,S根据该值计算玩家要去的点回复给C
type MsgMove struct {
	// 账号
	AccountId *string `protobuf:"bytes,1,opt,name=AccountId" json:"AccountId,omitempty"`
	// 目标点
	TargetPos        *MsgPosInfo `protobuf:"bytes,2,opt,name=TargetPos" json:"TargetPos,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MsgMove) Reset()                    { *m = MsgMove{} }
func (m *MsgMove) String() string            { return proto.CompactTextString(m) }
func (*MsgMove) ProtoMessage()               {}
func (*MsgMove) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MsgMove) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *MsgMove) GetTargetPos() *MsgPosInfo {
	if m != nil {
		return m.TargetPos
	}
	return nil
}

// 单点结构
type MsgPosStruct struct {
	// 账号
	AccountId *string `protobuf:"bytes,1,opt,name=AccountId" json:"AccountId,omitempty"`
	// x
	PosX *float32 `protobuf:"fixed32,2,opt,name=PosX" json:"PosX,omitempty"`
	// y
	PosY             *float32 `protobuf:"fixed32,3,opt,name=PosY" json:"PosY,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgPosStruct) Reset()                    { *m = MsgPosStruct{} }
func (m *MsgPosStruct) String() string            { return proto.CompactTextString(m) }
func (*MsgPosStruct) ProtoMessage()               {}
func (*MsgPosStruct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MsgPosStruct) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *MsgPosStruct) GetPosX() float32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *MsgPosStruct) GetPosY() float32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

// 服务器心跳同步到客户端
type MsgAddTargetPos struct {
	// 玩家新增点位
	PosList          []*MsgPosStruct `protobuf:"bytes,1,rep,name=PosList" json:"PosList,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *MsgAddTargetPos) Reset()                    { *m = MsgAddTargetPos{} }
func (m *MsgAddTargetPos) String() string            { return proto.CompactTextString(m) }
func (*MsgAddTargetPos) ProtoMessage()               {}
func (*MsgAddTargetPos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MsgAddTargetPos) GetPosList() []*MsgPosStruct {
	if m != nil {
		return m.PosList
	}
	return nil
}

// 食物结构
type MsgFoodStruct struct {
	// id
	Id *uint32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	// x
	PosX *float32 `protobuf:"fixed32,2,opt,name=PosX" json:"PosX,omitempty"`
	// y
	PosY *float32 `protobuf:"fixed32,3,opt,name=PosY" json:"PosY,omitempty"`
	// 半径
	Radius *float32 `protobuf:"fixed32,4,opt,name=Radius" json:"Radius,omitempty"`
	// 分数
	Score            *uint32 `protobuf:"varint,5,opt,name=Score" json:"Score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgFoodStruct) Reset()                    { *m = MsgFoodStruct{} }
func (m *MsgFoodStruct) String() string            { return proto.CompactTextString(m) }
func (*MsgFoodStruct) ProtoMessage()               {}
func (*MsgFoodStruct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MsgFoodStruct) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MsgFoodStruct) GetPosX() float32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *MsgFoodStruct) GetPosY() float32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

func (m *MsgFoodStruct) GetRadius() float32 {
	if m != nil && m.Radius != nil {
		return *m.Radius
	}
	return 0
}

func (m *MsgFoodStruct) GetScore() uint32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

// 添加食物
type MsgAddFood struct {
	// 食物
	FoodList         []*MsgFoodStruct `protobuf:"bytes,1,rep,name=FoodList" json:"FoodList,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MsgAddFood) Reset()                    { *m = MsgAddFood{} }
func (m *MsgAddFood) String() string            { return proto.CompactTextString(m) }
func (*MsgAddFood) ProtoMessage()               {}
func (*MsgAddFood) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MsgAddFood) GetFoodList() []*MsgFoodStruct {
	if m != nil {
		return m.FoodList
	}
	return nil
}

// 删除食物
type MsgDelFood struct {
	FoodList         []uint32 `protobuf:"varint,1,rep,name=FoodList" json:"FoodList,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgDelFood) Reset()                    { *m = MsgDelFood{} }
func (m *MsgDelFood) String() string            { return proto.CompactTextString(m) }
func (*MsgDelFood) ProtoMessage()               {}
func (*MsgDelFood) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MsgDelFood) GetFoodList() []uint32 {
	if m != nil {
		return m.FoodList
	}
	return nil
}

// 房间数据
type MsgRoomData struct {
	// 房间id
	RoomId *uint32 `protobuf:"varint,1,opt,name=RoomId" json:"RoomId,omitempty"`
	// 宽(对应x)
	RoomW *float32 `protobuf:"fixed32,2,opt,name=RoomW" json:"RoomW,omitempty"`
	// 高(对应y)
	RoomH *float32 `protobuf:"fixed32,3,opt,name=RoomH" json:"RoomH,omitempty"`
	// 玩家数量
	PlayerCount *uint32 `protobuf:"varint,4,opt,name=PlayerCount" json:"PlayerCount,omitempty"`
	// 现有玩家列表
	AccountIdList    []string `protobuf:"bytes,5,rep,name=AccountIdList" json:"AccountIdList,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgRoomData) Reset()                    { *m = MsgRoomData{} }
func (m *MsgRoomData) String() string            { return proto.CompactTextString(m) }
func (*MsgRoomData) ProtoMessage()               {}
func (*MsgRoomData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MsgRoomData) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MsgRoomData) GetRoomW() float32 {
	if m != nil && m.RoomW != nil {
		return *m.RoomW
	}
	return 0
}

func (m *MsgRoomData) GetRoomH() float32 {
	if m != nil && m.RoomH != nil {
		return *m.RoomH
	}
	return 0
}

func (m *MsgRoomData) GetPlayerCount() uint32 {
	if m != nil && m.PlayerCount != nil {
		return *m.PlayerCount
	}
	return 0
}

func (m *MsgRoomData) GetAccountIdList() []string {
	if m != nil {
		return m.AccountIdList
	}
	return nil
}

// 房间,C发送查看房间信息到S,S回复房间信息给C
type MsgRoomInfo struct {
	// 房间列表
	RoomList         []*MsgRoomData `protobuf:"bytes,4,rep,name=RoomList" json:"RoomList,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MsgRoomInfo) Reset()                    { *m = MsgRoomInfo{} }
func (m *MsgRoomInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgRoomInfo) ProtoMessage()               {}
func (*MsgRoomInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MsgRoomInfo) GetRoomList() []*MsgRoomData {
	if m != nil {
		return m.RoomList
	}
	return nil
}

// 进入房间
type MsgRoomEnter struct {
	// 房间id
	RoomId *uint32 `protobuf:"varint,1,opt,name=RoomId" json:"RoomId,omitempty"`
	// 账号
	AccountId *string `protobuf:"bytes,2,opt,name=AccountId" json:"AccountId,omitempty"`
	// 宽(对应x)
	RoomW *float32 `protobuf:"fixed32,3,opt,name=RoomW" json:"RoomW,omitempty"`
	// 高(对应y)
	RoomH *float32 `protobuf:"fixed32,4,opt,name=RoomH" json:"RoomH,omitempty"`
	// 玩家数量
	PlayerCount *uint32 `protobuf:"varint,5,opt,name=PlayerCount" json:"PlayerCount,omitempty"`
	// 现有玩家列表
	PlayerList       []*MsgPlayerInfo `protobuf:"bytes,6,rep,name=PlayerList" json:"PlayerList,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MsgRoomEnter) Reset()                    { *m = MsgRoomEnter{} }
func (m *MsgRoomEnter) String() string            { return proto.CompactTextString(m) }
func (*MsgRoomEnter) ProtoMessage()               {}
func (*MsgRoomEnter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MsgRoomEnter) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MsgRoomEnter) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *MsgRoomEnter) GetRoomW() float32 {
	if m != nil && m.RoomW != nil {
		return *m.RoomW
	}
	return 0
}

func (m *MsgRoomEnter) GetRoomH() float32 {
	if m != nil && m.RoomH != nil {
		return *m.RoomH
	}
	return 0
}

func (m *MsgRoomEnter) GetPlayerCount() uint32 {
	if m != nil && m.PlayerCount != nil {
		return *m.PlayerCount
	}
	return 0
}

func (m *MsgRoomEnter) GetPlayerList() []*MsgPlayerInfo {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

// 退出房间，C无需参数，S无需参数
type MsgExitRoom struct {
	// 账号
	AccountId        *string `protobuf:"bytes,1,opt,name=AccountId" json:"AccountId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgExitRoom) Reset()                    { *m = MsgExitRoom{} }
func (m *MsgExitRoom) String() string            { return proto.CompactTextString(m) }
func (*MsgExitRoom) ProtoMessage()               {}
func (*MsgExitRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MsgExitRoom) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

// 错误码
type MsgError struct {
	// 错误码
	ErrorIdx         *uint32 `protobuf:"varint,1,opt,name=ErrorIdx" json:"ErrorIdx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgError) Reset()                    { *m = MsgError{} }
func (m *MsgError) String() string            { return proto.CompactTextString(m) }
func (*MsgError) ProtoMessage()               {}
func (*MsgError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *MsgError) GetErrorIdx() uint32 {
	if m != nil && m.ErrorIdx != nil {
		return *m.ErrorIdx
	}
	return 0
}

// 心跳包
type MsgHeartbeat struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgHeartbeat) Reset()                    { *m = MsgHeartbeat{} }
func (m *MsgHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*MsgHeartbeat) ProtoMessage()               {}
func (*MsgHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func init() {
	proto.RegisterType((*MsgMsgData)(nil), "MsgMsgData")
	proto.RegisterType((*MsgMsgInit)(nil), "MsgMsgInit")
	proto.RegisterType((*MsgPosInfo)(nil), "MsgPosInfo")
	proto.RegisterType((*MsgPlayerInfo)(nil), "MsgPlayerInfo")
	proto.RegisterType((*MsgLogin)(nil), "MsgLogin")
	proto.RegisterType((*MsgMove)(nil), "MsgMove")
	proto.RegisterType((*MsgPosStruct)(nil), "MsgPosStruct")
	proto.RegisterType((*MsgAddTargetPos)(nil), "MsgAddTargetPos")
	proto.RegisterType((*MsgFoodStruct)(nil), "MsgFoodStruct")
	proto.RegisterType((*MsgAddFood)(nil), "MsgAddFood")
	proto.RegisterType((*MsgDelFood)(nil), "MsgDelFood")
	proto.RegisterType((*MsgRoomData)(nil), "MsgRoomData")
	proto.RegisterType((*MsgRoomInfo)(nil), "MsgRoomInfo")
	proto.RegisterType((*MsgRoomEnter)(nil), "MsgRoomEnter")
	proto.RegisterType((*MsgExitRoom)(nil), "MsgExitRoom")
	proto.RegisterType((*MsgError)(nil), "MsgError")
	proto.RegisterType((*MsgHeartbeat)(nil), "MsgHeartbeat")
	proto.RegisterEnum("TErrorType", TErrorType_name, TErrorType_value)
	proto.RegisterEnum("TPosShapeType", TPosShapeType_name, TPosShapeType_value)
}

func init() { proto.RegisterFile("snake.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x93, 0x5f, 0x6f, 0xd3, 0x3c,
	0x14, 0xc6, 0x97, 0xfe, 0x5d, 0x4f, 0xeb, 0x2e, 0xaf, 0x5f, 0x21, 0xe5, 0x62, 0x54, 0x95, 0x2f,
	0x50, 0x35, 0x41, 0x24, 0xb8, 0x86, 0x8b, 0x89, 0x0d, 0x2d, 0xd2, 0x52, 0x2a, 0x5a, 0xc1, 0x76,
	0x69, 0x6a, 0x93, 0x46, 0x64, 0x71, 0x67, 0x3b, 0xd3, 0xf6, 0x0d, 0xf8, 0x14, 0x7c, 0x56, 0xe4,
	0x93, 0xb4, 0x69, 0x47, 0xc5, 0x55, 0x73, 0xec, 0xa7, 0xe7, 0xfc, 0xce, 0x73, 0x8e, 0xa1, 0x6f,
	0x72, 0xfe, 0x53, 0x86, 0x6b, 0xad, 0xac, 0x62, 0xaf, 0x01, 0x62, 0x93, 0xc4, 0x26, 0xb9, 0xe0,
	0x96, 0x53, 0x02, 0xed, 0xd8, 0x24, 0x91, 0x08, 0xbc, 0xb1, 0x37, 0x21, 0xf4, 0x04, 0xba, 0xb1,
	0x49, 0xa6, 0xfc, 0x4e, 0x06, 0x8d, 0xb1, 0x37, 0xe9, 0xb1, 0xb3, 0x8d, 0x3a, 0xca, 0x53, 0x4b,
	0x4f, 0xf1, 0xfa, 0x3a, 0x35, 0x36, 0xf0, 0xc6, 0xcd, 0x49, 0xff, 0x5d, 0x3f, 0xac, 0x73, 0xb1,
	0x09, 0x6a, 0x67, 0xca, 0x44, 0xf9, 0x0f, 0x45, 0x07, 0xd0, 0x9a, 0x29, 0x73, 0x83, 0x89, 0x1b,
	0x55, 0x74, 0x8b, 0x59, 0x1b, 0xec, 0xb7, 0x07, 0xc4, 0x49, 0x33, 0xfe, 0x24, 0x35, 0xaa, 0xff,
	0x83, 0xde, 0xf9, 0x72, 0xa9, 0x8a, 0xdc, 0x56, 0x2c, 0x3d, 0x3a, 0x84, 0xce, 0x17, 0xa5, 0xee,
	0x22, 0x81, 0x7f, 0x22, 0x94, 0x02, 0x5c, 0xa4, 0x5a, 0x2e, 0x6d, 0xaa, 0xf2, 0x9b, 0xa0, 0x89,
	0x69, 0x77, 0xcf, 0x6e, 0x83, 0x16, 0x9e, 0x11, 0x68, 0xcf, 0xd7, 0x52, 0x8a, 0xa0, 0x8d, 0xe1,
	0x0b, 0x20, 0xf3, 0x42, 0xaf, 0xb3, 0xc2, 0x5c, 0xcb, 0x3c, 0xb1, 0xab, 0xa0, 0x83, 0xd9, 0x4e,
	0xa1, 0x3b, 0x53, 0x06, 0x5b, 0xe9, 0xd6, 0xad, 0x54, 0xf0, 0xec, 0x25, 0x1c, 0xbb, 0x46, 0x55,
	0x92, 0xe6, 0x07, 0xd0, 0xd8, 0x7b, 0xf4, 0x21, 0x56, 0x0f, 0xf2, 0x10, 0xf8, 0x08, 0x7a, 0x0b,
	0xae, 0x13, 0x69, 0x67, 0xca, 0x20, 0xfb, 0xb3, 0xe4, 0x1f, 0x60, 0x50, 0x46, 0x73, 0xab, 0x8b,
	0xa5, 0x3d, 0x94, 0x62, 0x63, 0x5e, 0x63, 0xcf, 0x3c, 0xec, 0x99, 0xbd, 0x85, 0x93, 0xd8, 0x24,
	0xe7, 0x42, 0x6c, 0x8b, 0xd0, 0x51, 0xdd, 0x4c, 0x39, 0x17, 0x12, 0xee, 0x56, 0x60, 0x5f, 0xd1,
	0xee, 0x4f, 0x4a, 0x89, 0xaa, 0x24, 0x40, 0x63, 0x3b, 0xf3, 0x7f, 0xd4, 0xc2, 0x19, 0x70, 0x91,
	0x16, 0x66, 0xc7, 0xdb, 0xa5, 0xd2, 0x12, 0xbd, 0x25, 0x2c, 0xc4, 0x89, 0x9f, 0x0b, 0xe1, 0x52,
	0xd3, 0x31, 0x1c, 0xbb, 0xdf, 0x1d, 0x8c, 0x61, 0xb8, 0x57, 0x96, 0x8d, 0x50, 0x7f, 0x21, 0x33,
	0xd4, 0xfb, 0xcf, 0xf4, 0x84, 0x25, 0xd0, 0x8f, 0x4d, 0xe2, 0xa6, 0x8e, 0xcb, 0x59, 0x6f, 0x40,
	0x49, 0x4a, 0xa0, 0xed, 0xe2, 0x6f, 0x15, 0x6a, 0x15, 0x5e, 0x55, 0xac, 0xff, 0x43, 0xbf, 0x5c,
	0xa8, 0x8f, 0xce, 0x4a, 0x04, 0x26, 0x6e, 0xfa, 0x5b, 0x6f, 0xb1, 0x50, 0x7b, 0xdc, 0x9c, 0xf4,
	0xd8, 0x9b, 0x6d, 0x21, 0xdc, 0xbe, 0x11, 0x1c, 0xbb, 0x6f, 0x14, 0xb4, 0x90, 0x7c, 0x10, 0xee,
	0x80, 0xb0, 0x5f, 0x1e, 0x8e, 0xcc, 0xc5, 0x97, 0xb9, 0x95, 0xfa, 0x2f, 0xb2, 0xbd, 0x11, 0xe2,
	0xcb, 0xa9, 0x61, 0x9b, 0xfb, 0xb0, 0xad, 0x43, 0xb0, 0x68, 0x27, 0x65, 0x00, 0xe5, 0x21, 0x82,
	0x74, 0x6a, 0x0b, 0xeb, 0x87, 0xc2, 0xc6, 0x48, 0x7e, 0xf9, 0x98, 0x5a, 0x97, 0xee, 0xd0, 0x72,
	0x9e, 0xe2, 0xee, 0x5e, 0x6a, 0xad, 0xb4, 0xb3, 0x18, 0x3f, 0x22, 0xf1, 0x58, 0x92, 0xb2, 0x21,
	0x76, 0x72, 0x25, 0xb9, 0xb6, 0xdf, 0x25, 0xb7, 0x67, 0xf7, 0x00, 0x0b, 0x94, 0x2c, 0x9e, 0xd6,
	0x92, 0xf6, 0xa1, 0x1b, 0xe5, 0x0f, 0x3c, 0x4b, 0x85, 0x7f, 0x44, 0x7d, 0x18, 0x94, 0x4d, 0x46,
	0x66, 0x5a, 0x64, 0x99, 0xef, 0x51, 0x0a, 0xc3, 0x12, 0x65, 0xaa, 0xa2, 0xdc, 0xdd, 0xf9, 0x0d,
	0xa7, 0xda, 0xe0, 0xe1, 0x49, 0x93, 0x0e, 0x37, 0x6d, 0x44, 0x66, 0xaa, 0xfc, 0x96, 0x8b, 0x3f,
	0xdb, 0x95, 0xd4, 0xf8, 0x9c, 0xfc, 0xf6, 0xd9, 0x2b, 0x20, 0x0b, 0xb7, 0x9b, 0x2b, 0xbe, 0x96,
	0x58, 0x15, 0xa0, 0x33, 0xbf, 0x2f, 0xb8, 0x96, 0xfe, 0x11, 0xed, 0x39, 0x9f, 0x8a, 0x5c, 0xf8,
	0xde, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0x97, 0x62, 0x7b, 0xb7, 0x04, 0x00, 0x00,
}
